#!/bin/sh
VEGETA=`which vegeta`
LOGDIR=attack_results
DATE=`date +%Y%m%d%H%M`

# Usage
# echo test_scenario_A.txt | ./vegeta_attack.sh

if [ -p /dev/stdin ] ; then
    TESTNAME=$(cat -)
    echo "シナリオ: ${TESTNAME} を実行"
else
    echo "テストシナリオ名を入力してください"
fi

if [ ! -e ${LOGDIR} ]; then
  mkdir -p ${LOGDIR}
fi

echo "攻撃を実行中…"
cat ./test_scenario/${TESTNAME}.txt | ${VEGETA} attack -duration=1s --rate 1 | tee ${LOGDIR}/${TESTNAME}_${DATE}.bin | ${VEGETA} report
